server:
  port: 9300 # 服务端口

spring:
  application:
    name: eureka-server # 服务名

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9301/eureka/
  instance:
    hostname: localhost