/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.sc.user2.domain.tables;


import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import top.zbeboy.sc.user2.domain.Indexes;
import top.zbeboy.sc.user2.domain.Keys;
import top.zbeboy.sc.user2.domain.Sc;
import top.zbeboy.sc.user2.domain.tables.records.UsersRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends TableImpl<UsersRecord> {

    private static final long serialVersionUID = -110366222;

    /**
     * The reference instance of <code>sc.users</code>
     */
    public static final Users USERS = new Users();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersRecord> getRecordType() {
        return UsersRecord.class;
    }

    /**
     * The column <code>sc.users.username</code>.
     */
    public final TableField<UsersRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>sc.users.password</code>.
     */
    public final TableField<UsersRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR(300).nullable(false), this, "");

    /**
     * The column <code>sc.users.enabled</code>.
     */
    public final TableField<UsersRecord, Byte> ENABLED = createField("enabled", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>sc.users.real_name</code>.
     */
    public final TableField<UsersRecord, String> REAL_NAME = createField("real_name", org.jooq.impl.SQLDataType.VARCHAR(30), this, "");

    /**
     * The column <code>sc.users.mobile</code>.
     */
    public final TableField<UsersRecord, String> MOBILE = createField("mobile", org.jooq.impl.SQLDataType.VARCHAR(15).nullable(false), this, "");

    /**
     * The column <code>sc.users.avatar</code>.
     */
    public final TableField<UsersRecord, String> AVATAR = createField("avatar", org.jooq.impl.SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>sc.users.verify_mailbox</code>.
     */
    public final TableField<UsersRecord, Byte> VERIFY_MAILBOX = createField("verify_mailbox", org.jooq.impl.SQLDataType.TINYINT, this, "");

    /**
     * The column <code>sc.users.mailbox_verify_code</code>.
     */
    public final TableField<UsersRecord, String> MAILBOX_VERIFY_CODE = createField("mailbox_verify_code", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>sc.users.password_reset_key</code>.
     */
    public final TableField<UsersRecord, String> PASSWORD_RESET_KEY = createField("password_reset_key", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>sc.users.mailbox_verify_valid</code>.
     */
    public final TableField<UsersRecord, Timestamp> MAILBOX_VERIFY_VALID = createField("mailbox_verify_valid", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sc.users.password_reset_key_valid</code>.
     */
    public final TableField<UsersRecord, Timestamp> PASSWORD_RESET_KEY_VALID = createField("password_reset_key_valid", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>sc.users.lang_key</code>.
     */
    public final TableField<UsersRecord, String> LANG_KEY = createField("lang_key", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>sc.users.join_date</code>.
     */
    public final TableField<UsersRecord, Date> JOIN_DATE = createField("join_date", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * Create a <code>sc.users</code> table reference
     */
    public Users() {
        this(DSL.name("users"), null);
    }

    /**
     * Create an aliased <code>sc.users</code> table reference
     */
    public Users(String alias) {
        this(DSL.name(alias), USERS);
    }

    /**
     * Create an aliased <code>sc.users</code> table reference
     */
    public Users(Name alias) {
        this(alias, USERS);
    }

    private Users(Name alias, Table<UsersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Users(Name alias, Table<UsersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sc.SC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.USERS_MOBILE, Indexes.USERS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UsersRecord> getPrimaryKey() {
        return Keys.KEY_USERS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UsersRecord>> getKeys() {
        return Arrays.<UniqueKey<UsersRecord>>asList(Keys.KEY_USERS_PRIMARY, Keys.KEY_USERS_MOBILE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users as(String alias) {
        return new Users(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Users as(Name alias) {
        return new Users(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(String name) {
        return new Users(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Users rename(Name name) {
        return new Users(name, null);
    }
}
