server:
  port: 8200 # 服务端口

spring:
  application:
    name: sso-server # 服务名
  data:
    rest:
      base-path: /login

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9300/eureka/,http://localhost:9301/eureka/
  instance:
    hostname: localhost