/*
 * This file is generated by jOOQ.
*/
package top.zbeboy.sc.user1.domain;


import javax.annotation.Generated;

import top.zbeboy.sc.user1.domain.tables.Users;


/**
 * Convenience access to all tables in sc
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sc.users</code>.
     */
    public static final Users USERS = top.zbeboy.sc.user1.domain.tables.Users.USERS;
}
