server:
  port: 8301 # 服务端口

spring:
  application:
    name: api-server # 服务名
zuul:
  routes:
    sso-serve:
      path: /sso/**
      service-id: sso-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9300/eureka/,http://localhost:9301/eureka/
  instance:
    hostname: localhost